config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # ゲストログイン用ルーティングの追加
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]

    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search' => 'searches#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: {in:2..20}
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  ## 仮想テーブル内の:follower, :followedに対して Relationship内からデータを引っ張ってきていることを明示
  # フォローする人(フォローするユーザーから見た中間(仮想)テーブル)
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされる人(フォローされているユーザーから見た中間(仮想)テーブル)
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 仮想テーブル follower を通り、フォローされる側(followed)を集める処理をfollowing_userと命名
  # フォローしているユーザーのデータが確認可能
  has_many :following_user, through: :follower, source: :followed
  # 仮想テーブル followed を通り、フォローする側(follower)を集める処理をfollowerと命名
  # フォローされているユーザーのデータが確認可能
  has_many :follower_user, through: :followed, source: :follower


  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # ユーザーをフォローする
  def follow(user)
    follower.create(followed_id: user.id)
  end

  # ユーザーのフォローを外す
  def unfollow(user)
    follower.find_by(followed_id: user.id).destroy
  end

  # フォローの確認を行う
  def following?(user)
    following_user.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward' # 前方一致
      User.where('name LIKE ?', content+'%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%'+content)
    else
      User.where('name LIKE ?', '%'+content+'%')
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "ゲストユーザー"
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def guest_sign_in
    # Modelのguestメソッドを呼び出し
    user = User.guest
    sign_in user
    redirect_to books_path, notice: 'ゲストユーザーでログインしています'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render 'edit'
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  private
  # ストロングパラメーターに住所関連のカラムを追加
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :email, :postcode, :prefecture_code, :address_city, :address_street, :address_building)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<h3>
<% if user.errors.any? %>
  <%= user.errors.count %>errors prohibited this obj from being saved:
</h3>
<ul>
  <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(50, 50) %></td>
      <td><%= user.name %></td>
      <td><%= render "relationships/link", user: user %></td>
      <td><%= link_to "Show", user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100, 100) %><br />
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>

    <% if user == current_user %>
      <tr>
        <th>Mail address</th>
        <th><%= user.email %></th>
      </tr>
      <tr>
        <th>post_code</th>
        <th><%= user.postcode %></th>
      </tr>
      <tr>
        <th>address</th>
        <th><%= user.join_address %></th>
      </tr>
    <% end %>

    <tr>
      <th>Map</th>
      <th>
        <script type="text/javascript">
          function initMap() {
            var test ={lat: <%= user.latitude %>, lng: <%= user.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
                      zoom: 15, 
                      center: test
                      });
            var transitLayer = new google.maps.TransitLayer();
            transitLayer.setMap(map);

            var contentString = '住所：<%= user.join_address %>';
            var infowindow = new google.maps.InfoWindow({
              content: contentString
            });
            var marker = new google.maps.Marker({
                          position:test,
                          map: map,
                          title: contentString
                        });

            marker.addListener('click', function() {
              infowindow.open(map, marker);
            });
          }
        </script>

        <script async defer
                      src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap">
        </script>
        <style type="text/css">
          #map { height: 400px;
                width: 100%;}
        </style>

        <div id="map"></div>
      </th>
    </tr>

    <tr>
      <th>follows</th>
      <th><%= link_to user.following_user.count, user_followings_path(user) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.follower_user.count, user_followers_path(user) %></th>
    </tr>
    <tr>
      <th><%= render "relationships/btn", user: user %></th>
      <th colspan='2'></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <% if @user.email == 'guest@example.com' %>
      <p>ゲストユーザーは編集できません</p>
    <% else %>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model: @user, local:true do |f| %>
          <%= render 'errors', user: @user %>
          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name, autofocus: true, class: "form-control name", id:"user_name", placeholder:"名前" %>
          </div>
          <div class="form-group">
            <label for="user_image">Image</label>
            <%= f.file_field :profile_image, class: "form-control-file user_image", placeholder: "プロフィール画像", accept: "image/*" %>
          </div>
          <div class="form-group">
            <label for="user_introduction">Introduction</label>
            <%= f.text_area :introduction, class: "form-control introduction", autofocus: true, class: "form-control name", id:"user_introduction" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/book', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/book', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(50, 50) %><br />
              <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book.id) %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <%= month_calendar events: @reservations do |date, reservations| %>
      <%= date %>

      <% reservations.each do |reservation| %>
        <div>
          <%= reservation.start_time.hour %>:<%= reservation.start_time.min %>
          <%= reservation.title %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>